export const fileKindLabels = {
  code: "Code",
  test: "Test",
  styles: "Styles",
  docs: "Docs",
  config: "Config",
  data: "Data",
  table: "Table",
  database: "Database",
  script: "Script",
  lockfile: "Lockfile",
  image: "Image",
  font: "Font",
  video: "Video",
  audio: "Audio",
  archive: "Archive",
};
export type FileKind = keyof typeof fileKindLabels;

const lockfiles = new Set([
  "bun.lock",
  "bun.lockb",
  "cargo.lock",
  "composer.lock",
  "deno.lock",
  "flake.lock",
  "gemfile.lock",
  "go.sum",
  "mix.lock",
  "npm-shrinkwrap.json",
  "package-lock.json",
  "packages.lock.json",
  "pipfile.lock",
  "pnpm-lock.yaml",
  "podfile.lock",
  "poetry.lock",
  "pubspec.lock",
  "uv.lock",
  "yarn.lock",
]);
const names: Record<string, FileKind> = {
  authors: "docs",
  brewfile: "config",
  changelog: "docs",
  codeowners: "config",
  "composer.json": "config",
  contributing: "docs",
  copying: "docs",
  "deno.json": "config",
  gemfile: "config",
  gnumakefile: "script",
  "go.mod": "config",
  jenkinsfile: "config",
  justfile: "script",
  licence: "docs",
  license: "docs",
  makefile: "script",
  notice: "docs",
  "package.json": "config",
  pipfile: "config",
  podfile: "config",
  procfile: "config",
  rakefile: "script",
  readme: "docs",
  "renovate.json": "config",
  "turbo.json": "config",
  vagrantfile: "config",
  "vercel.json": "config",
};
const extensions: Record<string, FileKind> = {
  adoc: "docs",
  markdown: "docs",
  md: "docs",
  mdx: "docs",
  rst: "docs",
  txt: "docs",
  css: "styles",
  less: "styles",
  pcss: "styles",
  sass: "styles",
  scss: "styles",
  styl: "styles",
  cfg: "config",
  conf: "config",
  env: "config",
  ini: "config",
  json5: "config",
  jsonc: "config",
  properties: "config",
  toml: "config",
  yaml: "config",
  yml: "config",
  json: "data",
  jsonl: "data",
  ndjson: "data",
  xml: "data",
  csv: "table",
  tsv: "table",
  xls: "table",
  xlsx: "table",
  prisma: "database",
  sql: "database",
  bash: "script",
  bat: "script",
  cmd: "script",
  fish: "script",
  mk: "script",
  ps1: "script",
  sh: "script",
  zsh: "script",
  avif: "image",
  bmp: "image",
  gif: "image",
  heic: "image",
  ico: "image",
  jpeg: "image",
  jpg: "image",
  png: "image",
  svg: "image",
  tif: "image",
  tiff: "image",
  webp: "image",
  eot: "font",
  otf: "font",
  ttf: "font",
  woff: "font",
  woff2: "font",
  mkv: "video",
  mov: "video",
  mp4: "video",
  webm: "video",
  flac: "audio",
  m4a: "audio",
  mp3: "audio",
  ogg: "audio",
  wav: "audio",
  "7z": "archive",
  bz2: "archive",
  gz: "archive",
  jar: "archive",
  rar: "archive",
  tar: "archive",
  tgz: "archive",
  xz: "archive",
  zip: "archive",
};
const testDirectory = /(^|\/)(__tests__|__mocks__|__snapshots__|tests?|spec|e2e)\//i;
const testName = /[._-](test|spec)\.|^test_.*\.py$|^conftest\.py$|Tests?\.(java|kt|cs|swift)$|\.snap$/;
const configName =
  /^\.|\.config\.[^.]+$|^[jt]sconfig(\..+)?\.json$|^(docker|container)file(\..+)?$|^requirements.*\.txt$/;

export function fileKind(path: string, image = false): FileKind {
  const base = path.split("/").at(-1)!;
  const name = base.toLowerCase();
  const extension = name.includes(".") ? name.split(".").at(-1)! : "";
  if (image) return "image";
  if (lockfiles.has(name)) return "lockfile";
  if (testDirectory.test(path) || testName.test(base)) return "test";
  // A file named constructor or toString must not resolve to Object.prototype.
  if (Object.hasOwn(names, name)) return names[name];
  if (configName.test(name)) return "config";
  return Object.hasOwn(extensions, extension) ? extensions[extension] : "code";
}
